from dp5.nmr_processing.proton.integrate import find_integrals, weighted_region_centres
from dp5.nmr_processing.proton.peak_picking import gradient_peak_picking
from dp5.nmr_processing.proton.fid_corrections import spectral_processing
from dp5.nmr_processing.proton.solvent_removal import solvent_removal
from dp5.nmr_processing.proton.bic_minimisation import multiproc_BIC_minimisation
from dp5.nmr_processing.proton.simulate import simulate_regions
